import { useEffect, useRef, useState } from 'react';
import { View } from 'react-native';
import Animated, { runOnJS, useAnimatedReaction, useAnimatedStyle, useSharedValue, type SharedValue } from 'react-native-reanimated';
import Svg, { Line, Polygon } from 'react-native-svg';

type HitWipeTransitionProps = {
  isHit: boolean;
  lineDrawProgress: SharedValue<number>;
  hitWipeProgress: SharedValue<number>;
  settleOffsetX: SharedValue<number>;
  settleOffsetY: SharedValue<number>;
  buttonAnchor: { x: number; y: number };
  fillColor: string;
  // Now received as props, generated by the hook instead of internally --
  // the hook needs the actual chosen values itself to compute genuine
  // distance-to-edge geometry for the draw duration, so this is now the
  // single source of truth rather than being duplicated in two places.
  angles: { top: number; bottom: number } | null;
  margin: number;
  // Each parametrization direction (minus/plus) gets its own, genuine
  // distance-to-edge -- computed by the hook using a sign-aware formula
  // (verified numerically) that correctly identifies which edge each
  // direction actually travels toward, rather than assuming "minus
  // always reaches 0, plus always reaches screenWidth" (which silently
  // breaks whenever cosine goes negative, i.e. left-handed angles).
  // No handedness remapping needed here -- this component already
  // determines genuine left/right via direct x-comparison.
  hitLineDistances: { topMinus: number; topPlus: number; bottomMinus: number; bottomPlus: number };
  // Needed to fix two real bugs (both verified numerically before this
  // fix): (1) the naive "minus cos = left, plus cos = right" endpoint
  // labeling breaks for left-handed angles, where cosine goes negative --
  // producing an actually-swapped, self-intersecting polygon. (2) the
  // flatten-to-flat transition needs to target 180deg for left-handed
  // lines, not 0deg -- otherwise it swings through a chaotic near-full
  // rotation instead of a simple flatten.
  isRightHanded: boolean;
};

const EDGE_OVERSHOOT = 200;
// Once the moving boundary's leading edge (in its direction of travel)
// clears past the fixed line's own far endpoint, the moving boundary's
// angle transitions toward 0 (flat) over this fraction of the total
// fillProgress range -- kept short deliberately, so a genuine majority
// of the wipe (after the threshold) reads as flat, not gradually
// straightening the whole time.
const FLATTEN_WINDOW_FRACTION = 0.1;

// Shared by both lines -- computed once the geometry (line angle, its
// intercept, its travel target) is known. Solves for the exact
// fillProgress at which the moving boundary's trailing edge (relative to
// its own direction of travel) clears past the fixed line's own far
// endpoint. Verified numerically (both directions) before writing this in.
function computeFlattenThreshold(lineY: number, targetIntercept: number, spread: number) {
  const range = Math.abs(targetIntercept - lineY);
  if (range === 0) return 1;
  return Math.min(1, Math.max(0, (2 * spread) / range));
}

export function HitWipeTransition({
  isHit,
  lineDrawProgress,
  hitWipeProgress,
  settleOffsetX,
  settleOffsetY,
  buttonAnchor,
  fillColor,
  angles,
  margin,
  hitLineDistances,
  isRightHanded,
}: HitWipeTransitionProps) {
  const containerRef = useRef<any>(null);
  const [measured, setMeasured] = useState<{ x: number; y: number; width: number; height: number } | null>(null);
  const [ballPosition, setBallPosition] = useState<{ x: number; y: number } | null>(null);
  const [drawProgress, setDrawProgress] = useState(0);
  const [fillProgress, setFillProgress] = useState(0);

  function handleLayout() {
    containerRef.current?.measureInWindow((x: number, y: number, width: number, height: number) => {
      setMeasured({ x, y, width, height });
    });
  }

  useEffect(() => {
    if (isHit) {
      setBallPosition({
        x: buttonAnchor.x + settleOffsetX.value,
        y: buttonAnchor.y + settleOffsetY.value,
      });
    }
  }, [isHit]);

  const lastDrawBridgeTime = useSharedValue(0);
  const lastFillBridgeTime = useSharedValue(0);
  const THROTTLE_MS = 30;

  useAnimatedReaction(
    () => lineDrawProgress.value,
    (current) => {
      const now = Date.now();
      if (now - lastDrawBridgeTime.value < THROTTLE_MS && current > 0 && current < 1) return;
      lastDrawBridgeTime.value = now;
      runOnJS(setDrawProgress)(current);
    }
  );

  useAnimatedReaction(
    () => hitWipeProgress.value,
    (current) => {
      const now = Date.now();
      if (now - lastFillBridgeTime.value < THROTTLE_MS && current > 0 && current < 1) return;
      lastFillBridgeTime.value = now;
      runOnJS(setFillProgress)(current);
    }
  );

  const containerOpacityStyle = useAnimatedStyle(() => ({
    opacity: lineDrawProgress.value > 0 || hitWipeProgress.value > 0 ? 1 : 0,
  }));

  // Robust endpoint labeling -- computes both raw points, then determines
  // genuine left/right via direct X-comparison, rather than assuming
  // "minus cos = left, plus cos = right." That assumption silently breaks
  // for left-handed angles (roughly 135-225deg), where cosine goes
  // negative -- verified numerically that it swapped the labels entirely,
  // producing a self-intersecting, criss-crossed polygon.
  //
  // Now takes two SEPARATE lengths (minus/plus direction) instead of one
  // shared length -- each side of a line can legitimately need a
  // different distance to reach its own edge.
  function computeAsymmetricPoints(centerX: number, centerY: number, rad: number, minusLength: number, plusLength: number) {
    const p1 = [centerX - minusLength * Math.cos(rad), centerY - minusLength * Math.sin(rad)];
    const p2 = [centerX + plusLength * Math.cos(rad), centerY + plusLength * Math.sin(rad)];
    return p1[0] < p2[0] ? { left: p1, right: p2 } : { left: p2, right: p1 };
  }

  let content = null;
  if (isHit && measured && ballPosition && angles) {
    const fullLineLength = measured.width * 1.5; // wipe/moving-boundary's own, deliberately over-sized extent -- unrelated to the drawn line's target

    const topLineY = ballPosition.y - margin;
    const bottomLineY = ballPosition.y + margin;
    const topRad = (angles.top * Math.PI) / 180;
    const bottomRad = (angles.bottom * Math.PI) / 180;

    // The "flat" reference for this handedness -- 0deg for right-handed,
    // 180deg for left-handed.
    const handednessCenterRad = isRightHanded ? 0 : Math.PI;

    // No handedness remapping needed anymore -- these are already the
    // correct minus/plus distances directly from the hook.
    const topMinusTarget = hitLineDistances.topMinus;
    const topPlusTarget = hitLineDistances.topPlus;
    const bottomMinusTarget = hitLineDistances.bottomMinus;
    const bottomPlusTarget = hitLineDistances.bottomPlus;

    // Both sides grow along the SAME shared drawProgress timeline, but
    // each is capped at its own target once reached -- the shorter side
    // visually stops exactly at its real edge while the longer side
    // keeps extending toward its own, further target.
    const topRawLength = drawProgress * Math.max(topMinusTarget, topPlusTarget);
    const bottomRawLength = drawProgress * Math.max(bottomMinusTarget, bottomPlusTarget);
    const topCurrentMinus = Math.min(topRawLength, topMinusTarget);
    const topCurrentPlus = Math.min(topRawLength, topPlusTarget);
    const bottomCurrentMinus = Math.min(bottomRawLength, bottomMinusTarget);
    const bottomCurrentPlus = Math.min(bottomRawLength, bottomPlusTarget);

    // Fixed lines -- always at their original, drawn angle, never flattened.
    const { left: topLeft, right: topRight } = computeAsymmetricPoints(
      ballPosition.x,
      topLineY,
      topRad,
      topCurrentMinus,
      topCurrentPlus
    );
    const { left: bottomLeft, right: bottomRight } = computeAsymmetricPoints(
      ballPosition.x,
      bottomLineY,
      bottomRad,
      bottomCurrentMinus,
      bottomCurrentPlus
    );

    const topTargetIntercept = -EDGE_OVERSHOOT;
    const bottomTargetIntercept = measured.height + EDGE_OVERSHOOT;

    const topSpread = fullLineLength * Math.abs(Math.sin(topRad));
    const bottomSpread = fullLineLength * Math.abs(Math.sin(bottomRad));

    const topThreshold = computeFlattenThreshold(topLineY, topTargetIntercept, topSpread);
    const bottomThreshold = computeFlattenThreshold(bottomLineY, bottomTargetIntercept, bottomSpread);

    const topFlattenProgress =
      fillProgress <= topThreshold ? 0 : Math.min(1, (fillProgress - topThreshold) / FLATTEN_WINDOW_FRACTION);
    const bottomFlattenProgress =
      fillProgress <= bottomThreshold ? 0 : Math.min(1, (fillProgress - bottomThreshold) / FLATTEN_WINDOW_FRACTION);

    // Moving boundary's OWN angle, interpolating toward the correct
    // handedness reference (0 or PI) once its flatten window is active --
    // previously this always interpolated toward raw 0, which for
    // left-handed lines meant swinging through a chaotic ~180deg
    // rotation instead of a simple flatten. The fixed line above is
    // completely unaffected by this, only the moving/traveling edge changes.
    const topMovingRad = handednessCenterRad + (topRad - handednessCenterRad) * (1 - topFlattenProgress);
    const bottomMovingRad = handednessCenterRad + (bottomRad - handednessCenterRad) * (1 - bottomFlattenProgress);

    const topCurrentIntercept = topLineY * (1 - fillProgress) + topTargetIntercept * fillProgress;
    const { left: topMovingLeft, right: topMovingRight } = computeAsymmetricPoints(
      ballPosition.x,
      topCurrentIntercept,
      topMovingRad,
      fullLineLength,
      fullLineLength
    );

    const bottomCurrentIntercept = bottomLineY * (1 - fillProgress) + bottomTargetIntercept * fillProgress;
    const { left: bottomMovingLeft, right: bottomMovingRight } = computeAsymmetricPoints(
      ballPosition.x,
      bottomCurrentIntercept,
      bottomMovingRad,
      fullLineLength,
      fullLineLength
    );

    const topPolygonPoints = `${topLeft[0]},${topLeft[1]} ${topRight[0]},${topRight[1]} ${topMovingRight[0]},${topMovingRight[1]} ${topMovingLeft[0]},${topMovingLeft[1]}`;
    const bottomPolygonPoints = `${bottomLeft[0]},${bottomLeft[1]} ${bottomRight[0]},${bottomRight[1]} ${bottomMovingRight[0]},${bottomMovingRight[1]} ${bottomMovingLeft[0]},${bottomMovingLeft[1]}`;

    content = (
      <Svg width={measured.width} height={measured.height}>
        {fillProgress > 0 && <Polygon points={topPolygonPoints} fill={fillColor} />}
        {fillProgress > 0 && <Polygon points={bottomPolygonPoints} fill={fillColor} />}
        <Line x1={topLeft[0]} y1={topLeft[1]} x2={topRight[0]} y2={topRight[1]} stroke={fillColor} strokeWidth={3} />
        <Line
          x1={bottomLeft[0]}
          y1={bottomLeft[1]}
          x2={bottomRight[0]}
          y2={bottomRight[1]}
          stroke={fillColor}
          strokeWidth={3}
        />
      </Svg>
    );
  }

  return (
    <View
      ref={containerRef}
      onLayout={handleLayout}
      style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }}
      pointerEvents="none"
    >
      <Animated.View style={[{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }, containerOpacityStyle]}>
        {content}
      </Animated.View>
    </View>
  );
}