BASE_URL = "https://statsapi.mlb.com/api/v1"

# Qualification thresholds -- all three mirror the "one season equivalent" convention
PA_QUALIFICATION_THRESHOLD = 502
IP_QUALIFICATION_THRESHOLD = 162.0
POSITION_ELIGIBILITY_GAMES_THRESHOLD = 162

CAREER_START_DATE = "1900-01-01"

# Bootstrap vars for initial seed data -- "career as of end of 2025 season"
BOOTSTRAP_END_DATE = "2025-11-01"
BOOTSTRAP_START_SEASON = 2025
ERA_FLOOR_SEASON = 1901
TEAM_BATCH_SIZE = 30

# The fielding endpoint reports OF positions separately; the schema tracks one combined OF bucket
OUTFIELD_POSITION_ABBREVIATIONS = {"LF", "CF", "RF"}
TRACKED_FIELDING_POSITIONS = {"C", "1B", "2B", "3B", "SS", "OF"}

REQUEST_PACING_SECONDS = 1
REQUEST_TIMEOUT_SECONDS = 30
MAX_RETRIES = 4
RETRY_BACKOFF_SECONDS = 3

CIRCUIT_BREAKER_FAILURE_THRESHOLD = 3
CIRCUIT_BREAKER_COOLDOWN_SECONDS = 180
CIRCUIT_BREAKER_MAX_TRIPS_PER_RUN = 2